run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - misspell
    - revive
  disable:
    - godot
    - wsl

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enable-all: false
    disabled-checks:
      - hugeParam
  revive:
    severity: warning
    rules:
      - name: exported
        disabled: true
      - name: if-return
      - name: indent-error-flow
      - name: superfluous-else
      - name: unexported-return
  misspell:
    locale: US

issues:
  exclude-use-default: false
  exclude-dirs:
    - vendor
  exclude-rules:
    # Allow benign unchecked returns for user-facing logging IO
    - text: "Error return value of `fmt\.Fprint"
      linters: [errcheck]
    - text: "Error return value of `fmt\.Fprintln"
      linters: [errcheck]
    - text: "Error return value of `fmt\.Fprintf"
      linters: [errcheck]
    - text: "Error return value of `resp\.Body\.Close`"
      linters: [errcheck]
    - text: "Error return value of `filepath\.Abs`"
      linters: [errcheck]
    - text: "Error return value of `filepath\.Rel`"
      linters: [errcheck]
    - text: "Error return value of `d\.Info`"
      linters: [errcheck]
    - text: "Error return value of `http\.NewRequest`"
      linters: [errcheck]
    - path: _test\.go
      linters:
        - errcheck
        - revive
    - path: internal/engine/filters\.go
      text: "DefaultGeneratedIgnores|defaultExclude"
      linters:
        - revive


